### ISSUE TITLE
(Random) Issues found during playtesting on 9/17, 18

### ISSUE THREAD

**Issue by erichoco** [UIUC-games-research/spatial-cs#27]
I'm just writing them down in case I forget.
### Cannot move field of view with mouse (exploration)

When the user enters exploration mode for the second time (i.e. after finishing constructing tutorials and rocketboots,) the user cannot move the perspective with mouse. (Right-clicking still works.)
5 of 6 kids playtesting encountered this issue.
### Rotate arrows not responding (construction)

In construction mode Tutorial 1, _some_ kids couldn't rotate the components with arrows. The components would still translate slightly just like when the rotation is working.

**Comment by Nolenz** [comment]
(Rotation Gizmo) If it's specifically tutorial 1, I don't think we have to worry about it too much. I remember Helen talking about scrapping those tutorial scenes (?)

**Comment by erichoco** [comment]
Okay, I see. But we couldn't skip them in Full Game mode right?

**Comment by Nolenz** [comment]
Nope, not at the time. I was just about to build a new version with some fixes, so I'll quickly add a way to skip those tutorial scenes.

**Comment by erichoco** [comment]
Got it thanks!

**Comment by Nolenz** [comment]
Apparently trying to skip out of the tutorial scenes silently breaks everything. I'm running out of time here, so I'm just going to provide two executables for now: One with tutorials included, one without.
